# SUSY Les Houches Accord 2 - VLQ+2LQ Spectrum + Decays + Flavor Observables
# SPheno module generated by SARAH
# ----------------------------------------------------------------------
# SPheno v4.0.3  
#   W. Porod, Comput. Phys. Commun. 153 (2003) 275-315, hep-ph/0301101
#   W. Porod, F.Staub, Comput.Phys.Commun.183 (2012) 2458-2469, arXiv:1104.1573
# SARAH: 4.13.0  
#   F. Staub; arXiv:0806.0538 (online manual)
#   F. Staub; Comput. Phys. Commun. 181 (2010) 1077-1086; arXiv:0909.2863
#   F. Staub; Comput. Phys. Commun. 182 (2011)  808-833; arXiv:1002.0840
#   F. Staub; Comput. Phys. Commun. 184 (2013)  1792-1809; arXiv:1207.0906
#   F. Staub; Comput. Phys. Commun. 185 (2014)  1773-1790; arXiv:1309.7223 
# Including the calculation of flavor observables based on the FlavorKit 
#   W. Porod, F. Staub, A. Vicente; Eur.Phys.J. C74 (2014) 8, 2992; arXiv:1405.1434 
# Two-loop masss corrections to Higgs fields based on 
#   M. D. Goodsell, K. Nickel, F. Staub; Eur.Phys.J. C75 (2015) no.6, 290; arXiv:1411.0675 
#   M. D. Goodsell, K. Nickel, F. Staub; Eur.Phys.J. C75 (2015) no.1, 32; arXiv:1503.03098
#   M. D. Goodsell, F. Staub; arXiv:1511.01904
#  
# in case of problems send email to florian.staub@kit.edu and goodsell@lpthe.jussieu.fr 
# ----------------------------------------------------------------------
# Created: 13.05.2018,  20:47
Block SPINFO         # Program information
     1   SPhenoSARAH      # spectrum calculator
     2   v4.0.3      # version number of SPheno
     9   4.13.0      # version number of SARAH
Block MODSEL  # Input parameters
     1  1   #  GUT scale input
     2  1   #  Boundary conditions 
     6  1   #  switching on flavour violation
Block MINPAR  # Input parameters
    1    1.70000000E-01  # Lambdainput
    2    0.00000000E+00  # LPhiinput
    3    1.50000000E+03  # mQinput
    4    7.50000000E+02  # MPhiinput
    5    0.00000000E+00  # gHPinput
    6    7.50000000E+02  # MTripinput
    7    0.00000000E+00  # lamMinput
    8    0.00000000E+00  # LTP1input
    9    0.00000000E+00  # LTP3input
   10    0.00000000E+00  # LT1input
   11    0.00000000E+00  # LT2input
   12    0.00000000E+00  # LHT1input
Block gaugeGUT Q= -1.00000000E+00  # (GUT scale)
   1    0.00000000E+00  # g1(Q)
   2    0.00000000E+00  # g2(Q)
   3    0.00000000E+00  # g3(Q)
Block SMINPUTS  # SM parameters
         1     1.27932000E+02  # alpha_em^-1(MZ)^MSbar
         2     1.16637000E-05  # G_mu [GeV^-2]
         3     1.18700000E-01  # alpha_s(MZ)^MSbar
         4     9.11887000E+01  # m_Z(pole)
         5     4.18000000E+00  # m_b(m_b), MSbar
         6     1.73500000E+02  # m_t(pole)
         7     1.77669000E+00  # m_tau(pole)
Block GAUGE Q=  1.60000000E+02  # (Renormalization Scale)
   1    3.55690247E-01  # g1
   2    6.62798598E-01  # g2
   3    1.22132231E+00  # g3
Block SM Q=  1.60000000E+02  # (Renormalization Scale)
   2    1.70000000E-01  # Lam
   1    5.15308833E+03  # Mu
Block GHP Q=  1.60000000E+02  # (Renormalization Scale)
   1    0.00000000E+00  # gHP
Block LPHI Q=  1.60000000E+02  # (Renormalization Scale)
   1    0.00000000E+00  # LPhi
Block LTP1 Q=  1.60000000E+02  # (Renormalization Scale)
   1    0.00000000E+00  # LTP1
Block LHT1 Q=  1.60000000E+02  # (Renormalization Scale)
   1    0.00000000E+00  # LHT1
Block LT1 Q=  1.60000000E+02  # (Renormalization Scale)
   1    0.00000000E+00  # LT1
Block LT2 Q=  1.60000000E+02  # (Renormalization Scale)
   1    0.00000000E+00  # LT2
Block LAMM Q=  1.60000000E+02  # (Renormalization Scale)
   1    0.00000000E+00  # lamM
Block LTP3 Q=  1.60000000E+02  # (Renormalization Scale)
   1    0.00000000E+00  # LTP3
Block MQ Q=  1.60000000E+02  # (Renormalization Scale)
   1    1.50000000E+03  # MQp
Block MPHI2 Q=  1.60000000E+02  # (Renormalization Scale)
   1    5.62500000E+05  # MPhi2
Block MTRIP2 Q=  1.60000000E+02  # (Renormalization Scale)
   1    5.62500000E+05  # MTrip2
Block HMIX Q=  1.60000000E+02  # (Renormalization Scale)
   3    2.46220569E+02  # v
Block TREESM Q=  1.60000000E+02  # (Renormalization Scale)
   1    5.15308833E+03  # Mu
Block LOOPSM Q=  1.60000000E+02  # (Renormalization Scale)
   1    0.00000000E+00  # Mu
Block Yb Q=  1.60000000E+02  # (Renormalization Scale)
   1    0.00000000E+00  # Real(Yb(1) ,dp)
   2    0.00000000E+00  # Real(Yb(2) ,dp)
   3    0.00000000E+00  # Real(Yb(3) ,dp)
Block Yu Q=  1.60000000E+02  # (Renormalization Scale)
  1  1     1.39897827E-05   # Real(Yu(1,1),dp)
  1  2    -1.64341904E-03   # Real(Yu(1,2),dp)
  1  3     5.92627039E-03   # Real(Yu(1,3),dp)
  2  1     3.23582995E-06   # Real(Yu(2,1),dp)
  2  2     7.10058961E-03   # Real(Yu(2,2),dp)
  2  3    -4.07545835E-02   # Real(Yu(2,3),dp)
  3  1     4.91802180E-08   # Real(Yu(3,1),dp)
  3  2     3.00419293E-04   # Real(Yu(3,2),dp)
  3  3     9.95678124E-01   # Real(Yu(3,3),dp)
Block Yd Q=  1.60000000E+02  # (Renormalization Scale)
  1  1     2.87184285E-05   # Real(Yd(1,1),dp)
  1  2     0.00000000E+00   # Real(Yd(1,2),dp)
  1  3     0.00000000E+00   # Real(Yd(1,3),dp)
  2  1     0.00000000E+00   # Real(Yd(2,1),dp)
  2  2     5.45650142E-04   # Real(Yd(2,2),dp)
  2  3     0.00000000E+00   # Real(Yd(2,3),dp)
  3  1     0.00000000E+00   # Real(Yd(3,1),dp)
  3  2     0.00000000E+00   # Real(Yd(3,2),dp)
  3  3     2.40086062E-02   # Real(Yd(3,3),dp)
Block Ye Q=  1.60000000E+02  # (Renormalization Scale)
  1  1     2.93501725E-06   # Real(Ye(1,1),dp)
  1  2     0.00000000E+00   # Real(Ye(1,2),dp)
  1  3     0.00000000E+00   # Real(Ye(1,3),dp)
  2  1     0.00000000E+00   # Real(Ye(2,1),dp)
  2  2     6.06868478E-04   # Real(Ye(2,2),dp)
  2  3     0.00000000E+00   # Real(Ye(2,3),dp)
  3  1     0.00000000E+00   # Real(Ye(3,1),dp)
  3  2     0.00000000E+00   # Real(Ye(3,2),dp)
  3  3     1.02047490E-02   # Real(Ye(3,3),dp)
Block LAMPC Q=  1.60000000E+02  # (Renormalization Scale)
   1    0.00000000E+00  # Real(lamPC(1) ,dp)
   2    0.00000000E+00  # Real(lamPC(2) ,dp)
   3    0.00000000E+00  # Real(lamPC(3) ,dp)
Block LAML Q=  1.60000000E+02  # (Renormalization Scale)
  1  1     1.00000000E-01   # Real(lamL(1,1),dp)
  1  2     1.00000000E-01   # Real(lamL(1,2),dp)
  1  3     1.00000000E-01   # Real(lamL(1,3),dp)
  2  1     1.00000000E-01   # Real(lamL(2,1),dp)
  2  2     1.00000000E-01   # Real(lamL(2,2),dp)
  2  3     1.00000000E-01   # Real(lamL(2,3),dp)
  3  1     1.00000000E-01   # Real(lamL(3,1),dp)
  3  2     1.00000000E-01   # Real(lamL(3,2),dp)
  3  3     1.00000000E-01   # Real(lamL(3,3),dp)
Block LAMR Q=  1.60000000E+02  # (Renormalization Scale)
  1  1     1.00000000E-01   # Real(lamR(1,1),dp)
  1  2     1.00000000E-01   # Real(lamR(1,2),dp)
  1  3     1.00000000E-01   # Real(lamR(1,3),dp)
  2  1     1.00000000E-01   # Real(lamR(2,1),dp)
  2  2     1.00000000E-01   # Real(lamR(2,2),dp)
  2  3     1.00000000E-01   # Real(lamR(2,3),dp)
  3  1     1.00000000E-01   # Real(lamR(3,1),dp)
  3  2     1.00000000E-01   # Real(lamR(3,2),dp)
  3  3     1.00000000E-01   # Real(lamR(3,3),dp)
Block lamTL Q=  1.60000000E+02  # (Renormalization Scale)
  1  1     0.00000000E+00   # Real(lamTL(1,1),dp)
  1  2     0.00000000E+00   # Real(lamTL(1,2),dp)
  1  3     0.00000000E+00   # Real(lamTL(1,3),dp)
  2  1     0.00000000E+00   # Real(lamTL(2,1),dp)
  2  2     0.00000000E+00   # Real(lamTL(2,2),dp)
  2  3     0.00000000E+00   # Real(lamTL(2,3),dp)
  3  1     0.00000000E+00   # Real(lamTL(3,1),dp)
  3  2     0.00000000E+00   # Real(lamTL(3,2),dp)
  3  3     0.00000000E+00   # Real(lamTL(3,3),dp)
Block lamTC Q=  1.60000000E+02  # (Renormalization Scale)
   1    0.00000000E+00  # Real(lamTC(1) ,dp)
   2    0.00000000E+00  # Real(lamTC(2) ,dp)
   3    0.00000000E+00  # Real(lamTC(3) ,dp)
Block MASS  # Mass spectrum
#   PDG code      mass          particle
        25     1.01519341E+02  # hh
        11     5.10998930E-04  # Fe_1
        13     1.05658372E-01  # Fe_2
        15     1.77669000E+00  # Fe_3
         1     5.00000000E-03  # Fd_1
         3     9.50000000E-02  # Fd_2
         5     4.18000000E+00  # Fd_3
         7     1.50000000E+03  # Fd_4
         2     2.50000000E-03  # Fu_1
         4     1.27000000E+00  # Fu_2
         6     1.73500000E+02  # Fu_3
        24     8.03497269E+01  # VWp
        23     9.11887000E+01  # VZ
        38     7.50000000E+02  # SLQ_1
        39     7.50000000E+02  # SLQ_2
         8     1.50000000E+03  # Fy
        52     7.50000000E+02  # Tp
        51     7.50000000E+02  # Tm
Block UDLMIX Q=  1.60000000E+02  # ()
  1  1     1.00000000E+00   # Real(ZDL(1,1),dp)
  1  2     0.00000000E+00   # Real(ZDL(1,2),dp)
  1  3     0.00000000E+00   # Real(ZDL(1,3),dp)
  1  4     0.00000000E+00   # Real(ZDL(1,4),dp)
  2  1     0.00000000E+00   # Real(ZDL(2,1),dp)
  2  2     1.00000000E+00   # Real(ZDL(2,2),dp)
  2  3     0.00000000E+00   # Real(ZDL(2,3),dp)
  2  4     0.00000000E+00   # Real(ZDL(2,4),dp)
  3  1     0.00000000E+00   # Real(ZDL(3,1),dp)
  3  2     0.00000000E+00   # Real(ZDL(3,2),dp)
  3  3     1.00000000E+00   # Real(ZDL(3,3),dp)
  3  4     0.00000000E+00   # Real(ZDL(3,4),dp)
  4  1     0.00000000E+00   # Real(ZDL(4,1),dp)
  4  2     0.00000000E+00   # Real(ZDL(4,2),dp)
  4  3     0.00000000E+00   # Real(ZDL(4,3),dp)
  4  4     1.00000000E+00   # Real(ZDL(4,4),dp)
Block UDRMIX Q=  1.60000000E+02  # ()
  1  1     1.00000000E+00   # Real(ZDR(1,1),dp)
  1  2     0.00000000E+00   # Real(ZDR(1,2),dp)
  1  3     0.00000000E+00   # Real(ZDR(1,3),dp)
  1  4     0.00000000E+00   # Real(ZDR(1,4),dp)
  2  1     0.00000000E+00   # Real(ZDR(2,1),dp)
  2  2     1.00000000E+00   # Real(ZDR(2,2),dp)
  2  3     0.00000000E+00   # Real(ZDR(2,3),dp)
  2  4     0.00000000E+00   # Real(ZDR(2,4),dp)
  3  1     0.00000000E+00   # Real(ZDR(3,1),dp)
  3  2     0.00000000E+00   # Real(ZDR(3,2),dp)
  3  3     1.00000000E+00   # Real(ZDR(3,3),dp)
  3  4     0.00000000E+00   # Real(ZDR(3,4),dp)
  4  1     0.00000000E+00   # Real(ZDR(4,1),dp)
  4  2     0.00000000E+00   # Real(ZDR(4,2),dp)
  4  3     0.00000000E+00   # Real(ZDR(4,3),dp)
  4  4     1.00000000E+00   # Real(ZDR(4,4),dp)
Block UULMIX Q=  1.60000000E+02  # ()
  1  1     1.00000000E+00   # Real(ZUL(1,1),dp)
  1  2     2.16840434E-19   # Real(ZUL(1,2),dp)
  1  3     0.00000000E+00   # Real(ZUL(1,3),dp)
  2  1    -2.16840434E-19   # Real(ZUL(2,1),dp)
  2  2     1.00000000E+00   # Real(ZUL(2,2),dp)
  2  3     0.00000000E+00   # Real(ZUL(2,3),dp)
  3  1     0.00000000E+00   # Real(ZUL(3,1),dp)
  3  2     0.00000000E+00   # Real(ZUL(3,2),dp)
  3  3     1.00000000E+00   # Real(ZUL(3,3),dp)
Block UURMIX Q=  1.60000000E+02  # ()
  1  1     9.74272160E-01   # Real(ZUR(1,1),dp)
  1  2     2.25348678E-01   # Real(ZUR(1,2),dp)
  1  3     3.42499367E-03   # Real(ZUR(1,3),dp)
  2  1    -2.25296231E-01   # Real(ZUR(2,1),dp)
  2  2     9.73419462E-01   # Real(ZUR(2,2),dp)
  2  3     4.11844653E-02   # Real(ZUR(2,3),dp)
  3  1     5.94690932E-03   # Real(ZUR(3,1),dp)
  3  2    -4.08965161E-02   # Real(ZUR(3,2),dp)
  3  3     9.99145690E-01   # Real(ZUR(3,3),dp)
Block UELMIX Q=  1.60000000E+02  # ()
  1  1     1.00000000E+00   # Real(ZEL(1,1),dp)
  1  2     0.00000000E+00   # Real(ZEL(1,2),dp)
  1  3     0.00000000E+00   # Real(ZEL(1,3),dp)
  2  1     0.00000000E+00   # Real(ZEL(2,1),dp)
  2  2     1.00000000E+00   # Real(ZEL(2,2),dp)
  2  3     0.00000000E+00   # Real(ZEL(2,3),dp)
  3  1     0.00000000E+00   # Real(ZEL(3,1),dp)
  3  2     0.00000000E+00   # Real(ZEL(3,2),dp)
  3  3     1.00000000E+00   # Real(ZEL(3,3),dp)
Block UERMIX Q=  1.60000000E+02  # ()
  1  1     1.00000000E+00   # Real(ZER(1,1),dp)
  1  2     0.00000000E+00   # Real(ZER(1,2),dp)
  1  3     0.00000000E+00   # Real(ZER(1,3),dp)
  2  1     0.00000000E+00   # Real(ZER(2,1),dp)
  2  2     1.00000000E+00   # Real(ZER(2,2),dp)
  2  3     0.00000000E+00   # Real(ZER(2,3),dp)
  3  1     0.00000000E+00   # Real(ZER(3,1),dp)
  3  2     0.00000000E+00   # Real(ZER(3,2),dp)
  3  3     1.00000000E+00   # Real(ZER(3,3),dp)
Block Vmix Q=  1.60000000E+02  # ()
  1  1     1.00000000E+00   # Real(Vmix(1,1),dp)
  1  2     0.00000000E+00   # Real(Vmix(1,2),dp)
  2  1     0.00000000E+00   # Real(Vmix(2,1),dp)
  2  2     1.00000000E+00   # Real(Vmix(2,2),dp)
Block SPheno # SPheno internal parameters 
         1    -1.00000000E+00  # ErrorLevel
         2     0.00000000E+00  # SPA_conventions
        11     1.00000000E+00  # Branching ratios
        13     1.00000000E+00  # 3 Body decays
        31    -1.00000000E+00  # GUT scale
        33     1.60000000E+02  # Renormalization scale
        34     1.00000000E-04  # Precision
        35     4.00000000E+01  # Iterations
        38     2.00000000E+00  # RGE level
        40     7.29735257E-03  # Alpha
        41     2.49520000E+00  # Gamma_Z
        42     2.06000000E+00  # Gamma_W
        50     1.00000000E+00  # Rotate negative fermion masses
        51     0.00000000E+00  # Switch to SCKM matrix
        52     0.00000000E+00  # Ignore negative masses
        53     0.00000000E+00  # Ignore negative masses at MZ
        55     0.00000000E+00  # Calculate one loop masses
        56     1.00000000E+00  # Calculate two-loop Higgs masses
        57     1.00000000E+00  # Calculate low energy
        60     1.00000000E+00  # Include kinetic mixing
        65     1.00000000E+00  # Solution of tadpole equation
Block HiggsBoundsInputHiggsCouplingsFermions # 
    1.00000000E+00    0.00000000E+00        3             25         5         5 # h_1 b b coupling 
    1.00000000E+00    0.00000000E+00        3             25         3         3 # h_1 s s coupling 
    1.00000000E+00    0.00000000E+00        3             25         6         6 # h_1 t t coupling  
    1.00000000E+00    0.00000000E+00        3             25         4         4 # h_1 c c coupling 
    1.00000000E+00    0.00000000E+00        3             25        15        15 # h_1 tau tau coupling 
    1.00000000E+00    0.00000000E+00        3             25        13        13 # h_1 mu mu coupling  
Block HiggsBoundsInputHiggsCouplingsBosons # 
    1.00000000E+00        3             25        24        24 # h_1 W W coupling 
    1.00000000E+00        3             25        23        23 # h_1 Z Z coupling  
    0.00000000E+00        3             25        23        22 # h_1 Z gamma coupling 
    1.03916450E+00        3             25        22        22 # h_1 gamma gamma coupling 
    1.02723781E+00        3             25        21        21 # h_1 g g coupling 
    0.00000000E+00        4             25        21        21        23 # h_1 g g Z coupling 
    0.00000000E+00        3             25        25        23 # h_1 h_1 Z coupling  
Block EFFHIGGSCOUPLINGS # values of loop-induced couplings 
        25           22           22     0.29964999E-04 # H-Photon-Photon 
        25           21           21     0.67211810E-04 # H-Gluon-Gluon 
        25           22           23     0.00000000E+00 # H-Photon-Z (not yet calculated by SPheno) 
Block SPhenoLowEnergy # low energy observables 
       1    8.35444850E+03  # T-parameter (1-loop BSM)
       2    6.52239477E-14  # S-parameter (1-loop BSM)
       3   -6.14755840E-01  # U-parameter (1-loop BSM)
      20    3.25868280E-11  # (g-2)_e
      21    6.74088081E-09  # (g-2)_mu
      22    1.15531844E-07  # (g-2)_tau
      23    0.00000000E+00  # EDM(e)
      24    0.00000000E+00  # EDM(mu)
      25    0.00000000E+00  # EDM(tau)
      39   -6.09655942E+01  # delta(rho)
Block FlavorKitQFV # quark flavor violating observables 
     200    3.14984064E-04  # BR(B->X_s gamma)
     201    9.99949409E-01  # BR(B->X_s gamma)/BR(B->X_s gamma)_SM
     300    1.16707455E-06  # BR(D->mu nu)
     301    2.13569743E+33  # BR(D->mu nu)/BR(D->mu nu)_SM
     400    5.95198559E-03  # BR(Ds->mu nu)
     401    1.01090374E+00  # BR(Ds->mu nu)/BR(Ds->mu nu)_SM
     402    5.75449623E-02  # BR(Ds->tau nu)
     403    1.00005527E+00  # BR(Ds->tau nu)/BR(Ds->tau nu)_SM
     500    5.59725335E-05  # BR(B->mu nu)
     501    0.00000000E+00  # BR(B->mu nu)/BR(B->mu nu)_SM
     502    6.40351508E-05  # BR(B->tau nu)
     503    0.00000000E+00  # BR(B->tau nu)/BR(B->tau nu)_SM
     600    2.35419197E-03  # BR(K->mu nu)
     601    4.02064840E+33  # BR(K->mu nu)/BR(K->mu nu)_SM
     602    9.88453203E-01  # R_K = BR(K->e nu)/(K->mu nu)
     603    6.37778772E+71  # R_K^SM = BR(K->e nu)_SM/(K->mu nu)_SM
    1900    1.91480353E+01  # Delta(M_Bs)
    1901    1.01325977E+00  # Delta(M_Bs)/Delta(M_Bs)_SM
    1902    5.18988915E-01  # Delta(M_Bd)
    1903    1.22871054E+00  # Delta(M_Bd)/Delta(M_Bd)_SM
    4000    6.57264974E-19  # BR(B^0_d->e e)
    4001    2.22448093E+39  # BR(B^0_d->e e)/BR(B^0_d->e e)_SM
    4002    6.80624108E-16  # BR(B^0_s->e e)
    4003    5.92000450E+33  # BR(B^0_s->e e)/BR(B^0_s->e e)_SM
    4004    4.09664332E-14  # BR(B^0_d->mu mu)
    4005    3.24560027E+39  # BR(B^0_d->mu mu)/BR(B^0_d->mu mu)_SM
    4006    4.64770747E-14  # BR(B^0_s->mu mu)
    4007    9.46285837E+30  # BR(B^0_s->mu mu)/BR(B^0_s->mu mu)_SM
    4008    8.63214757E-12  # BR(B^0_d->tau tau)
    4009    3.26411936E+39  # BR(B^0_d->tau tau)/BR(B^0_d->tau tau)_SM
    4010    1.19190834E-11  # BR(B^0_s->tau tau)
    4011    1.14417196E+31  # BR(B^0_s->tau tau)/BR(B^0_s->tau tau)_SM
    5000    2.91612144E+27  # BR(B-> s e e)
    5001    1.76169822E+33  # BR(B-> s e e)/BR(B-> s e e)_SM
    5002    2.84233282E+27  # BR(B-> s mu mu)
    5003    1.77115562E+33  # BR(B-> s mu mu)/BR(B-> s mu mu)_SM
    6000    1.08266513E-07  # BR(B -> K mu mu)
    6001    9.75373990E-01  # BR(B -> K mu mu)/BR(B -> K mu mu)_SM
    6002    1.08266513E-07  # BR(B -> K mu mu)
    6003    9.75373990E-01  # BR(B -> K mu mu)/BR(B -> K mu mu)_SM
    7000    6.55406509E-05  # BR(B->s nu nu)
    7001    2.55902901E+36  # BR(B->s nu nu)/BR(B->s nu nu)_SM
    7002    6.58102492E-05  # BR(B->D nu nu)
    7003    7.07220982E+44  # BR(B->D nu nu)/BR(B->D nu nu)_SM
    8000    1.02095771E-06  # BR(K^+ -> pi^+ nu nu)
    8001    4.87698895E+04  # BR(K^+ -> pi^+ nu nu)/BR(K^+ -> pi^+ nu nu)_SM
    8002    0.00000000E+00  # BR(K_L -> pi^0 nu nu)
    8003    0.00000000E+00  # BR(K_L -> pi^0 nu nu)/BR(K_L -> pi^0 nu nu)_SM
    9100    7.95471669E-15  # Delta(M_K)
    9102    4.08679597E+00  # Delta(M_K)/Delta(M_K)_SM
    9103    1.84370744E-03  # epsilon_K
    9104    1.00000000E+00  # epsilon_K/epsilon_K^SM
Block FlavorKitLFV # lepton flavor violating observables 
     701    5.39685121E-02  # BR(mu->e gamma)
     702    3.59472026E-05  # BR(tau->e gamma)
     703    3.59563131E-05  # BR(tau->mu gamma)
     800    4.99101301E-04  # CR(mu-e, Al)
     801    9.44868635E-04  # CR(mu-e, Ti)
     802    1.23268093E-03  # CR(mu-e, Sr)
     803    1.57202857E-03  # CR(mu-e, Sb)
     804    8.94156859E-04  # CR(mu-e, Au)
     805    8.52554729E-04  # CR(mu-e, Pb)
     901    4.01359238E-04  # BR(mu->3e)
     902    4.36403086E-07  # BR(tau->3e)
     903    9.58859563E-08  # BR(tau->3mu)
     904    8.73384940E-08  # BR(tau- -> e- mu+ mu-)
     905    4.27990638E-07  # BR(tau- -> mu- e+ e-)
     906    4.94647366E-14  # BR(tau- -> e+ mu- mu-)
     907    4.94647366E-14  # BR(tau- -> mu+ e- e-)
    1001    4.05579373E-11  # BR(Z->e mu)
    1002    4.06466719E-11  # BR(Z->e tau)
    1003    4.06522589E-11  # BR(Z->mu tau)
    1101    2.84005886E-06  # BR(h->e mu)
    1102    2.83832506E-06  # BR(h->e tau)
    1103    2.80650210E-06  # BR(h->mu tau)
    2001    3.10247160E-07  # BR(tau->e pi)
    2002    1.16110046E-07  # BR(tau->e eta)
    2003    6.62780350E-09  # BR(tau->e eta')
    2004    8.99692339E-09  # BR(tau->mu pi)
    2005    3.13621656E-09  # BR(tau->mu eta)
    2006    9.26080536E-11  # BR(tau->mu eta')
Block FWCOEF Q=  1.60000000E+02  # Wilson coefficients at scale Q 
     0305 4422   00   0     0.52328051E-26    # coeffC7sm
     0305 4422   00   2     0.46889417E-11    # coeffC7
     0305 4322   00   2     0.10656686E-12    # coeffC7p
     0305 4422   00   1     0.46889417E-11    # coeffC7NP
     0305 4322   00   1     0.10656686E-12    # coeffC7pNP
     0305 6421   00   0     0.43543408E-26    # coeffC8sm
     0305 6421   00   2    -0.14603099E-10    # coeffC8
     0305 6321   00   2    -0.33188861E-12    # coeffC8p
     0305 6421   00   1    -0.14603099E-10    # coeffC8NP
     0305 6321   00   1    -0.33188861E-12    # coeffC8pNP
 03051111 4133   00   0     0.50825023E-27    # coeffC9eeSM
 03051111 4133   00   2    -0.70068733E-10    # coeffC9ee
 03051111 4233   00   2    -0.50081614E-15    # coeffC9Pee
 03051111 4133   00   1    -0.70068733E-10    # coeffC9eeNP
 03051111 4233   00   1    -0.50081614E-15    # coeffC9PeeNP
 03051111 4137   00   0    -0.48125733E-26    # coeffC10eeSM
 03051111 4137   00   2     0.16356169E-10    # coeffC10ee
 03051111 4237   00   2    -0.49345871E-15    # coeffC10Pee
 03051111 4137   00   1     0.16356169E-10    # coeffC10eeNP
 03051111 4237   00   1     0.49345871E-15    # coeffC10PeeNP
 03051313 4133   00   0     0.50824897E-27    # coeffC9mumuSM
 03051313 4133   00   2    -0.70068756E-10    # coeffC9mumu
 03051313 4233   00   2    -0.50081614E-15    # coeffC9Pmumu
 03051313 4133   00   1    -0.70068756E-10    # coeffC9mumuNP
 03051313 4233   00   1    -0.50081614E-15    # coeffC9PmumuNP
 03051313 4137   00   0    -0.48125745E-26    # coeffC10mumuSM
 03051313 4137   00   2     0.16356146E-10    # coeffC10mumu
 03051313 4237   00   2    -0.49345871E-15    # coeffC10Pmumu
 03051313 4137   00   1     0.16356146E-10    # coeffC10mumuNP
 03051313 4237   00   1    -0.49345871E-15    # coeffC10PmumuNP
 03051212 4141   00   0    -0.96251465E-26    # coeffCLnu1nu1SM
 03051212 4141   00   2     0.88888889E-08    # coeffCLnu1nu1
 03051212 4241   00   2     0.00000000E+00    # coeffCLPnu1nu1
 03051212 4141   00   1     0.88888889E-08    # coeffCLnu1nu1NP
 03051212 4241   00   1     0.00000000E+00    # coeffCLPnu1nu1NP
 03051414 4141   00   0    -0.96251379E-26    # coeffCLnu2nu2SM
 03051414 4141   00   2     0.88888889E-08    # coeffCLnu2nu2
 03051414 4241   00   2     0.00000000E+00    # coeffCLPnu2nu2
 03051414 4141   00   1     0.88888889E-08    # coeffCLnu2nu2NP
 03051414 4241   00   1     0.00000000E+00    # coeffCLPnu2nu2NP
 03051616 4141   00   0    -0.96227050E-26    # coeffCLnu3nu3SM
 03051616 4141   00   2     0.88888889E-08    # coeffCLnu3nu3
 03051616 4241   00   2     0.00000000E+00    # coeffCLPnu3nu3
 03051616 4141   00   1     0.88888889E-08    # coeffCLnu3nu3NP
 03051616 4241   00   1     0.00000000E+00    # coeffCLPnu3nu3NP
 03051212 4142   00   0     0.00000000E+00    # coeffCRnu1nu1SM
 03051212 4142   00   2    -0.88888889E-08    # coeffCRnu1nu1
 03051212 4242   00   2     0.00000000E+00    # coeffCRPnu1nu1
 03051212 4142   00   1    -0.88888889E-08    # coeffCRnu1nu1NP
 03051212 4242   00   1     0.00000000E+00    # coeffCRPnu1nu1NP
 03051414 4142   00   0     0.00000000E+00    # coeffCRnu2nu2SM
 03051414 4142   00   2    -0.88888889E-08    # coeffCRnu2nu2
 03051414 4242   00   2     0.00000000E+00    # coeffCRPnu2nu2
 03051414 4142   00   1    -0.88888889E-08    # coeffCRnu2nu2NP
 03051414 4242   00   1     0.00000000E+00    # coeffCRPnu2nu2NP
 03051616 4142   00   0     0.00000000E+00    # coeffCRnu3nu3SM
 03051616 4142   00   2    -0.88888889E-08    # coeffCRnu3nu3
 03051616 4242   00   2     0.00000000E+00    # coeffCRPnu3nu3
 03051616 4142   00   1    -0.88888889E-08    # coeffCRnu3nu3NP
 03051616 4242   00   1     0.00000000E+00    # coeffCRPnu3nu3NP
 01030103 3131   00   2    -0.99250860E-57    # coeffKK_SLL
 01030103 3232   00   2    -0.11863107E-54    # coeffKK_SRR
 01030103 3132   00   2    -0.46096406E-55    # coeffKK_SLR
 01030103 4141   00   2     0.12665148E-11    # coeffKK_VLL
 01030103 4242   00   2     0.33139381E-63    # coeffKK_VRR
 01030103 4142   00   2     0.83615157E-58    # coeffKK_VLR
 01030103 4343   00   2     0.00000000E+00    # coeffKK_TLL
 01030103 4444   00   2     0.00000000E+00    # coeffKK_TRR
 01050105 3131   00   2    -0.52034919E-59    # coeffBB_SLL
 01050105 3232   00   2     0.00000000E+00    # coeffBB_SRR
 01050105 3132   00   2     0.00000000E+00    # coeffBB_SLR
 01050105 4141   00   2     0.12665148E-11    # coeffBB_VLL
 01050105 4242   00   2     0.00000000E+00    # coeffBB_VRR
 01050105 4142   00   2     0.00000000E+00    # coeffBB_VLR
 01050105 4343   00   2     0.00000000E+00    # coeffBB_TLL
 01050105 4444   00   2     0.00000000E+00    # coeffBB_TRR
 03050305 3131   00   2    -0.88324791E-94    # coeffBsBs_SLL
 03050305 3232   00   2    -0.42974000E-48    # coeffBsBs_SRR
 03050305 3132   00   2    -0.53730550E-71    # coeffBsBs_SLR
 03050305 4141   00   2     0.12665148E-11    # coeffBsBs_VLL
 03050305 4242   00   2     0.00000000E+00    # coeffBsBs_VRR
 03050305 4142   00   2     0.00000000E+00    # coeffBsBs_VLR
 03050305 4343   00   2     0.00000000E+00    # coeffBsBs_TLL
 03050305 4444   00   2     0.00000000E+00    # coeffBsBs_TRR
 01030103 3131   00   1     0.00000000E+00    # coeffKK_SLLNP
 01030103 3232   00   1     0.00000000E+00    # coeffKK_SRRNP
 01030103 3132   00   1     0.00000000E+00    # coeffKK_SLRNP
 01030103 4141   00   1     0.12665148E-11    # coeffKK_VLLNP
 01030103 4242   00   1     0.00000000E+00    # coeffKK_VRRNP
 01030103 4142   00   1     0.00000000E+00    # coeffKK_VLRNP
 01030103 4343   00   1     0.00000000E+00    # coeffKK_TLLNP
 01030103 4444   00   1     0.00000000E+00    # coeffKK_TRRNP
 01050105 3131   00   1     0.00000000E+00    # coeffBB_SLLNP
 01050105 3232   00   1     0.00000000E+00    # coeffBB_SRRNP
 01050105 3132   00   1     0.00000000E+00    # coeffBB_SLRNP
 01050105 4141   00   1     0.12665148E-11    # coeffBB_VLLNP
 01050105 4242   00   1     0.00000000E+00    # coeffBB_VRRNP
 01050105 4142   00   1     0.00000000E+00    # coeffBB_VLRNP
 01050105 4343   00   1     0.00000000E+00    # coeffBB_TLLNP
 01050105 4444   00   1     0.00000000E+00    # coeffBB_TRRNP
 03050305 3131   00   1     0.00000000E+00    # coeffBsBs_SLLNP
 03050305 3232   00   1     0.00000000E+00    # coeffBsBs_SRRNP
 03050305 3132   00   1     0.00000000E+00    # coeffBsBs_SLRNP
 03050305 4141   00   1     0.12665148E-11    # coeffBsBs_VLLNP
 03050305 4242   00   1     0.00000000E+00    # coeffBsBs_VRRNP
 03050305 4142   00   1     0.00000000E+00    # coeffBsBs_VLRNP
 03050305 4343   00   1     0.00000000E+00    # coeffBsBs_TLLNP
 03050305 4444   00   1     0.00000000E+00    # coeffBsBs_TRRNP
 01030103 3131   00   0    -0.99250860E-57    # coeffKK_SLLSM
 01030103 3232   00   0    -0.11863107E-54    # coeffKK_SRRSM
 01030103 3132   00   0    -0.46096406E-55    # coeffKK_SLRSM
 01030103 4141   00   0     0.62626611E-49    # coeffKK_VLLSM
 01030103 4242   00   0     0.33139381E-63    # coeffKK_VRRSM
 01030103 4142   00   0     0.83615157E-58    # coeffKK_VLRSM
 01030103 4343   00   0     0.00000000E+00    # coeffKK_TLLSM
 01030103 4444   00   0     0.00000000E+00    # coeffKK_TRRSM
 01050105 3131   00   0    -0.52034919E-59    # coeffBB_SLLSM
 01050105 3232   00   0     0.00000000E+00    # coeffBB_SRRSM
 01050105 3132   00   0     0.00000000E+00    # coeffBB_SLRSM
 01050105 4141   00   0     0.18441673E-52    # coeffBB_VLLSM
 01050105 4242   00   0     0.00000000E+00    # coeffBB_VRRSM
 01050105 4142   00   0     0.00000000E+00    # coeffBB_VLRSM
 01050105 4343   00   0     0.00000000E+00    # coeffBB_TLLSM
 01050105 4444   00   0     0.00000000E+00    # coeffBB_TRRSM
 03050305 3131   00   0    -0.88324791E-94    # coeffBsBs_SLLSM
 03050305 3232   00   0    -0.42974000E-48    # coeffBsBs_SRRSM
 03050305 3132   00   0    -0.53730550E-71    # coeffBsBs_SLRSM
 03050305 4141   00   0     0.18431943E-45    # coeffBsBs_VLLSM
 03050305 4242   00   0     0.00000000E+00    # coeffBsBs_VRRSM
 03050305 4142   00   0     0.00000000E+00    # coeffBsBs_VLRSM
 03050305 4343   00   0     0.00000000E+00    # coeffBsBs_TLLSM
 03050305 4444   00   0     0.00000000E+00    # coeffBsBs_TRRSM
Block IMFWCOEF Q=  1.60000000E+02  # Im(Wilson coefficients) at scale Q 
     0305 4422   00   0    -0.00000000E+00    # coeffC7sm
     0305 4422   00   2    -0.00000000E+00    # coeffC7
     0305 4322   00   2    -0.00000000E+00    # coeffC7p
     0305 4422   00   1     0.00000000E+00    # coeffC7NP
     0305 4322   00   1    -0.00000000E+00    # coeffC7pNP
     0305 6421   00   0    -0.00000000E+00    # coeffC8sm
     0305 6421   00   2    -0.00000000E+00    # coeffC8
     0305 6321   00   2    -0.00000000E+00    # coeffC8p
     0305 6421   00   1     0.00000000E+00    # coeffC8NP
     0305 6321   00   1    -0.00000000E+00    # coeffC8pNP
 03051111 4133   00   0     0.00000000E+00    # coeffC9eeSM
 03051111 4133   00   2     0.00000000E+00    # coeffC9ee
 03051111 4233   00   2     0.00000000E+00    # coeffC9Pee
 03051111 4133   00   1     0.00000000E+00    # coeffC9eeNP
 03051111 4233   00   1     0.00000000E+00    # coeffC9PeeNP
 03051111 4137   00   0     0.00000000E+00    # coeffC10eeSM
 03051111 4137   00   2     0.00000000E+00    # coeffC10ee
 03051111 4237   00   2     0.00000000E+00    # coeffC10Pee
 03051111 4137   00   1     0.00000000E+00    # coeffC10eeNP
 03051111 4237   00   1     0.00000000E+00    # coeffC10PeeNP
 03051313 4133   00   0     0.00000000E+00    # coeffC9mumuSM
 03051313 4133   00   2     0.00000000E+00    # coeffC9mumu
 03051313 4233   00   2     0.00000000E+00    # coeffC9Pmumu
 03051313 4133   00   1     0.00000000E+00    # coeffC9mumuNP
 03051313 4233   00   1     0.00000000E+00    # coeffC9PmumuNP
 03051313 4137   00   0     0.00000000E+00    # coeffC10mumuSM
 03051313 4137   00   2     0.00000000E+00    # coeffC10mumu
 03051313 4237   00   2     0.00000000E+00    # coeffC10Pmumu
 03051313 4137   00   1     0.00000000E+00    # coeffC10mumuNP
 03051313 4237   00   1     0.00000000E+00    # coeffC10PmumuNP
 03051212 4141   00   0     0.00000000E+00    # coeffCLnu1nu1SM
 03051212 4141   00   2     0.00000000E+00    # coeffCLnu1nu1
 03051212 4241   00   2     0.00000000E+00    # coeffCLPnu1nu1
 03051212 4141   00   1     0.00000000E+00    # coeffCLnu1nu1NP
 03051212 4241   00   1     0.00000000E+00    # coeffCLPnu1nu1NP
 03051414 4141   00   0     0.00000000E+00    # coeffCLnu2nu2SM
 03051414 4141   00   2     0.00000000E+00    # coeffCLnu2nu2
 03051414 4241   00   2     0.00000000E+00    # coeffCLPnu2nu2
 03051414 4141   00   1     0.00000000E+00    # coeffCLnu2nu2NP
 03051414 4241   00   1     0.00000000E+00    # coeffCLPnu2nu2NP
 03051616 4141   00   0     0.00000000E+00    # coeffCLnu3nu3SM
 03051616 4141   00   2     0.00000000E+00    # coeffCLnu3nu3
 03051616 4241   00   2     0.00000000E+00    # coeffCLPnu3nu3
 03051616 4141   00   1     0.00000000E+00    # coeffCLnu3nu3NP
 03051616 4241   00   1     0.00000000E+00    # coeffCLPnu3nu3NP
 03051212 4142   00   0     0.00000000E+00    # coeffCRnu1nu1SM
 03051212 4142   00   2     0.00000000E+00    # coeffCRnu1nu1
 03051212 4242   00   2     0.00000000E+00    # coeffCRPnu1nu1
 03051212 4142   00   1     0.00000000E+00    # coeffCRnu1nu1NP
 03051212 4242   00   1     0.00000000E+00    # coeffCRPnu1nu1NP
 03051414 4142   00   0     0.00000000E+00    # coeffCRnu2nu2SM
 03051414 4142   00   2     0.00000000E+00    # coeffCRnu2nu2
 03051414 4242   00   2     0.00000000E+00    # coeffCRPnu2nu2
 03051414 4142   00   1     0.00000000E+00    # coeffCRnu2nu2NP
 03051414 4242   00   1     0.00000000E+00    # coeffCRPnu2nu2NP
 03051616 4142   00   0     0.00000000E+00    # coeffCRnu3nu3SM
 03051616 4142   00   2     0.00000000E+00    # coeffCRnu3nu3
 03051616 4242   00   2     0.00000000E+00    # coeffCRPnu3nu3
 03051616 4142   00   1     0.00000000E+00    # coeffCRnu3nu3NP
 03051616 4242   00   1     0.00000000E+00    # coeffCRPnu3nu3NP
 01030103 3131   00   2     0.00000000E+00    # coeffKK_SLL
 01030103 3232   00   2     0.00000000E+00    # coeffKK_SRR
 01030103 3132   00   2     0.00000000E+00    # coeffKK_SLR
 01030103 4141   00   2     0.00000000E+00    # coeffKK_VLL
 01030103 4242   00   2     0.00000000E+00    # coeffKK_VRR
 01030103 4142   00   2     0.00000000E+00    # coeffKK_VLR
 01030103 4343   00   2     0.00000000E+00    # coeffKK_TLL
 01030103 4444   00   2     0.00000000E+00    # coeffKK_TRR
 01050105 3131   00   2     0.00000000E+00    # coeffBB_SLL
 01050105 3232   00   2     0.00000000E+00    # coeffBB_SRR
 01050105 3132   00   2     0.00000000E+00    # coeffBB_SLR
 01050105 4141   00   2     0.00000000E+00    # coeffBB_VLL
 01050105 4242   00   2     0.00000000E+00    # coeffBB_VRR
 01050105 4142   00   2     0.00000000E+00    # coeffBB_VLR
 01050105 4343   00   2     0.00000000E+00    # coeffBB_TLL
 01050105 4444   00   2     0.00000000E+00    # coeffBB_TRR
 03050305 3131   00   2     0.00000000E+00    # coeffBsBs_SLL
 03050305 3232   00   2     0.00000000E+00    # coeffBsBs_SRR
 03050305 3132   00   2     0.00000000E+00    # coeffBsBs_SLR
 03050305 4141   00   2     0.00000000E+00    # coeffBsBs_VLL
 03050305 4242   00   2     0.00000000E+00    # coeffBsBs_VRR
 03050305 4142   00   2     0.00000000E+00    # coeffBsBs_VLR
 03050305 4343   00   2     0.00000000E+00    # coeffBsBs_TLL
 03050305 4444   00   2     0.00000000E+00    # coeffBsBs_TRR
 01030103 3131   00   1     0.00000000E+00    # coeffKK_SLLNP
 01030103 3232   00   1     0.00000000E+00    # coeffKK_SRRNP
 01030103 3132   00   1     0.00000000E+00    # coeffKK_SLRNP
 01030103 4141   00   1     0.00000000E+00    # coeffKK_VLLNP
 01030103 4242   00   1     0.00000000E+00    # coeffKK_VRRNP
 01030103 4142   00   1     0.00000000E+00    # coeffKK_VLRNP
 01030103 4343   00   1     0.00000000E+00    # coeffKK_TLLNP
 01030103 4444   00   1     0.00000000E+00    # coeffKK_TRRNP
 01050105 3131   00   1     0.00000000E+00    # coeffBB_SLLNP
 01050105 3232   00   1     0.00000000E+00    # coeffBB_SRRNP
 01050105 3132   00   1     0.00000000E+00    # coeffBB_SLRNP
 01050105 4141   00   1     0.00000000E+00    # coeffBB_VLLNP
 01050105 4242   00   1     0.00000000E+00    # coeffBB_VRRNP
 01050105 4142   00   1     0.00000000E+00    # coeffBB_VLRNP
 01050105 4343   00   1     0.00000000E+00    # coeffBB_TLLNP
 01050105 4444   00   1     0.00000000E+00    # coeffBB_TRRNP
 03050305 3131   00   1     0.00000000E+00    # coeffBsBs_SLLNP
 03050305 3232   00   1     0.00000000E+00    # coeffBsBs_SRRNP
 03050305 3132   00   1     0.00000000E+00    # coeffBsBs_SLRNP
 03050305 4141   00   1     0.00000000E+00    # coeffBsBs_VLLNP
 03050305 4242   00   1     0.00000000E+00    # coeffBsBs_VRRNP
 03050305 4142   00   1     0.00000000E+00    # coeffBsBs_VLRNP
 03050305 4343   00   1     0.00000000E+00    # coeffBsBs_TLLNP
 03050305 4444   00   1     0.00000000E+00    # coeffBsBs_TRRNP
 01030103 3131   00   0     0.00000000E+00    # coeffKK_SLLSM
 01030103 3232   00   0     0.00000000E+00    # coeffKK_SRRSM
 01030103 3132   00   0     0.00000000E+00    # coeffKK_SLRSM
 01030103 4141   00   0     0.00000000E+00    # coeffKK_VLLSM
 01030103 4242   00   0     0.00000000E+00    # coeffKK_VRRSM
 01030103 4142   00   0     0.00000000E+00    # coeffKK_VLRSM
 01030103 4343   00   0     0.00000000E+00    # coeffKK_TLLSM
 01030103 4444   00   0     0.00000000E+00    # coeffKK_TRRSM
 01050105 3131   00   0     0.00000000E+00    # coeffBB_SLLSM
 01050105 3232   00   0     0.00000000E+00    # coeffBB_SRRSM
 01050105 3132   00   0     0.00000000E+00    # coeffBB_SLRSM
 01050105 4141   00   0     0.00000000E+00    # coeffBB_VLLSM
 01050105 4242   00   0     0.00000000E+00    # coeffBB_VRRSM
 01050105 4142   00   0     0.00000000E+00    # coeffBB_VLRSM
 01050105 4343   00   0     0.00000000E+00    # coeffBB_TLLSM
 01050105 4444   00   0     0.00000000E+00    # coeffBB_TRRSM
 03050305 3131   00   0     0.00000000E+00    # coeffBsBs_SLLSM
 03050305 3232   00   0     0.00000000E+00    # coeffBsBs_SRRSM
 03050305 3132   00   0     0.00000000E+00    # coeffBsBs_SLRSM
 03050305 4141   00   0     0.00000000E+00    # coeffBsBs_VLLSM
 03050305 4242   00   0     0.00000000E+00    # coeffBsBs_VRRSM
 03050305 4142   00   0     0.00000000E+00    # coeffBsBs_VLRSM
 03050305 4343   00   0     0.00000000E+00    # coeffBsBs_TLLSM
 03050305 4444   00   0     0.00000000E+00    # coeffBsBs_TRRSM
DECAY         4     3.78829365E-13   # Fu_2
#    BR                NDA      ID1      ID2
#    BR                NDA      ID1      ID2       ID3
     6.08692131E-01    3            2         -1          3   # BR(Fu_2 -> Fu_1 Fd_1^* Fd_2 )
     2.00977516E-01    3            3        -11         12   # BR(Fu_2 -> Fd_2 Fe_1^* Fv_1 )
     1.90329847E-01    3            3        -13         14   # BR(Fu_2 -> Fd_2 Fe_2^* Fv_2 )
DECAY         6     1.55526379E+00   # Fu_3
#    BR                NDA      ID1      ID2
     9.99999978E-01    2            5         24   # BR(Fu_3 -> Fd_3 VWp )
DECAY        13     3.20012949E-19   # Fe_2
#    BR                NDA      ID1      ID2
#    BR                NDA      ID1      ID2       ID3
     9.99997603E-01    3           11         12         14   # BR(Fe_2 -> Fe_1 Fv_1 Fv_2 )
DECAY        15     2.16049056E-12   # Fe_3
#    BR                NDA      ID1      ID2
#    BR                NDA      ID1      ID2       ID3
     5.98957885E-01    3           16         -2          1   # BR(Fe_3 -> Fv_3 Fu_1^* Fd_1 )
     7.89629125E-03    3           16         -4          3   # BR(Fe_3 -> Fv_3 Fu_2^* Fd_2 )
     1.99214562E-01    3           11         12         16   # BR(Fe_3 -> Fe_1 Fv_1 Fv_3 )
     1.93930261E-01    3           13         14         16   # BR(Fe_3 -> Fe_2 Fv_2 Fv_3 )
DECAY         1     3.74799289E-14   # Fd_1
#    BR                NDA      ID1      ID2
#    BR                NDA      ID1      ID2       ID3
     1.00000000E+00    3            2         12         11   # BR(Fd_1 -> Fu_1 Fv_1 Fe_1 )
DECAY         3     2.06642620E-25   # Fd_2
#    BR                NDA      ID1      ID2
#    BR                NDA      ID1      ID2       ID3
     6.07790430E-02    3            1         12         12   # BR(Fd_2 -> Fd_1 Fv_1 Fv_1 )
     1.21558086E-01    3            1         12         14   # BR(Fd_2 -> Fd_1 Fv_1 Fv_2 )
     1.21558086E-01    3            1         12         16   # BR(Fd_2 -> Fd_1 Fv_1 Fv_3 )
     6.07790430E-02    3            1         14         14   # BR(Fd_2 -> Fd_1 Fv_2 Fv_2 )
     1.21558086E-01    3            1         14         16   # BR(Fd_2 -> Fd_1 Fv_2 Fv_3 )
     6.07790430E-02    3            1         16         16   # BR(Fd_2 -> Fd_1 Fv_3 Fv_3 )
     1.50996203E-01    3            2         12         11   # BR(Fd_2 -> Fu_1 Fv_1 Fe_1 )
     1.50996205E-01    3            2         14         11   # BR(Fd_2 -> Fu_1 Fv_2 Fe_1 )
     1.50996205E-01    3            2         16         11   # BR(Fd_2 -> Fu_1 Fv_3 Fe_1 )
DECAY         5     8.37210303E-17   # Fd_3
#    BR                NDA      ID1      ID2
#    BR                NDA      ID1      ID2       ID3
     2.52875519E-02    3            1         12         12   # BR(Fd_3 -> Fd_1 Fv_1 Fv_1 )
     5.05751038E-02    3            1         12         14   # BR(Fd_3 -> Fd_1 Fv_1 Fv_2 )
     5.05751038E-02    3            1         12         16   # BR(Fd_3 -> Fd_1 Fv_1 Fv_3 )
     2.52875519E-02    3            1         14         14   # BR(Fd_3 -> Fd_1 Fv_2 Fv_2 )
     5.05751038E-02    3            1         14         16   # BR(Fd_3 -> Fd_1 Fv_2 Fv_3 )
     2.52875519E-02    3            1         16         16   # BR(Fd_3 -> Fd_1 Fv_3 Fv_3 )
     2.51838736E-02    3            3         12         12   # BR(Fd_3 -> Fd_2 Fv_1 Fv_1 )
     5.03677472E-02    3            3         12         14   # BR(Fd_3 -> Fd_2 Fv_1 Fv_2 )
     5.03677472E-02    3            3         12         16   # BR(Fd_3 -> Fd_2 Fv_1 Fv_3 )
     2.51838736E-02    3            3         14         14   # BR(Fd_3 -> Fd_2 Fv_2 Fv_2 )
     5.03677472E-02    3            3         14         16   # BR(Fd_3 -> Fd_2 Fv_2 Fv_3 )
     2.51838736E-02    3            3         16         16   # BR(Fd_3 -> Fd_2 Fv_3 Fv_3 )
     6.18872014E-02    3            2         12         11   # BR(Fd_3 -> Fu_1 Fv_1 Fe_1 )
     6.15656031E-02    3            2         12         13   # BR(Fd_3 -> Fu_1 Fv_1 Fe_2 )
     1.67405964E-02    3            2         12         15   # BR(Fd_3 -> Fu_1 Fv_1 Fe_3 )
     6.18872014E-02    3            2         14         11   # BR(Fd_3 -> Fu_1 Fv_2 Fe_1 )
     6.15656031E-02    3            2         14         13   # BR(Fd_3 -> Fu_1 Fv_2 Fe_2 )
     1.67405964E-02    3            2         14         15   # BR(Fd_3 -> Fu_1 Fv_2 Fe_3 )
     6.18872014E-02    3            2         16         11   # BR(Fd_3 -> Fu_1 Fv_3 Fe_1 )
     6.15656031E-02    3            2         16         13   # BR(Fd_3 -> Fu_1 Fv_3 Fe_2 )
     1.67405964E-02    3            2         16         15   # BR(Fd_3 -> Fu_1 Fv_3 Fe_3 )
     2.09823435E-02    3            4         12         11   # BR(Fd_3 -> Fu_2 Fv_1 Fe_1 )
     1.97442579E-02    3            4         12         13   # BR(Fd_3 -> Fu_2 Fv_1 Fe_2 )
     9.99054584E-04    3            4         12         15   # BR(Fd_3 -> Fu_2 Fv_1 Fe_3 )
     2.09823435E-02    3            4         14         11   # BR(Fd_3 -> Fu_2 Fv_2 Fe_1 )
     1.97442579E-02    3            4         14         13   # BR(Fd_3 -> Fu_2 Fv_2 Fe_2 )
     9.99054584E-04    3            4         14         15   # BR(Fd_3 -> Fu_2 Fv_2 Fe_3 )
     2.09823435E-02    3            4         16         11   # BR(Fd_3 -> Fu_2 Fv_3 Fe_1 )
     1.97442579E-02    3            4         16         13   # BR(Fd_3 -> Fu_2 Fv_3 Fe_2 )
     9.99054584E-04    3            4         16         15   # BR(Fd_3 -> Fu_2 Fv_3 Fe_3 )
DECAY        25     2.38403499E-03   # hh
#    BR                NDA      ID1      ID2
     1.95989336E-03    2           22         22   # BR(hh -> VP VP )
     7.88832992E-02    2           21         21   # BR(hh -> VG VG )
     1.37335410E-04    2           23         23   # BR(hh -> VZ VZ )
     9.85047857E-03    2          -24         24   # BR(hh -> VWp^* VWp_virt )
     2.93029534E-04    2           -3          3   # BR(hh -> Fd_2^* Fd_2 )
     7.83728076E-01    2           -5          5   # BR(hh -> Fd_3^* Fd_3 )
     3.04233936E-04    2          -13         13   # BR(hh -> Fe_2^* Fe_2 )
     8.77626515E-02    2          -15         15   # BR(hh -> Fe_3^* Fe_3 )
     3.70800252E-02    2           -4          4   # BR(hh -> Fu_2^* Fu_2 )
DECAY        38     3.93827364E+00   # SLQ_1
#    BR                NDA      ID1      ID2
     3.78865902E-02    2           12          1   # BR(SLQ_1 -> Fv_1 Fd_1 )
     3.78865889E-02    2           12          3   # BR(SLQ_1 -> Fv_1 Fd_2 )
     3.78842365E-02    2           12          5   # BR(SLQ_1 -> Fv_1 Fd_3 )
     3.78865902E-02    2           14          1   # BR(SLQ_1 -> Fv_2 Fd_1 )
     3.78865889E-02    2           14          3   # BR(SLQ_1 -> Fv_2 Fd_2 )
     3.78842365E-02    2           14          5   # BR(SLQ_1 -> Fv_2 Fd_3 )
     3.78865902E-02    2           16          1   # BR(SLQ_1 -> Fv_3 Fd_1 )
     3.78865889E-02    2           16          3   # BR(SLQ_1 -> Fv_3 Fd_2 )
     3.78842365E-02    2           16          5   # BR(SLQ_1 -> Fv_3 Fd_3 )
     9.27205823E-02    2            2         11   # BR(SLQ_1 -> Fu_1 Fe_1 )
     9.27205786E-02    2            2         13   # BR(SLQ_1 -> Fu_1 Fe_2 )
     9.27195403E-02    2            2         15   # BR(SLQ_1 -> Fu_1 Fe_3 )
     6.14898346E-02    2            4         11   # BR(SLQ_1 -> Fu_2 Fe_1 )
     6.14898037E-02    2            4         13   # BR(SLQ_1 -> Fu_2 Fe_2 )
     6.14886648E-02    2            4         15   # BR(SLQ_1 -> Fu_2 Fe_3 )
     6.54932752E-02    2            6         11   # BR(SLQ_1 -> Fu_3 Fe_1 )
     6.54887869E-02    2            6         13   # BR(SLQ_1 -> Fu_3 Fe_2 )
     6.54166868E-02    2            6         15   # BR(SLQ_1 -> Fu_3 Fe_3 )
